name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Définir la bonne SECRET_KEY selon branche cible/source
        id: set-secret
        run: |
          branch_name="${{ github.event.pull_request.base.ref || github.ref_name }}"
          
          if [ "$branch_name" = "prod" ]; then
            echo "SECRET_KEY=${{ secrets.SECRET_KEY_PROD }}" >> $GITHUB_ENV
            echo "Longueur SECRET_KEY: ${#SECRET_KEY}"
          elif [ "$branch_name" = "preprod" ]; then
            echo "SECRET_KEY=${{ secrets.SECRET_KEY_PREPROD }}" >> $GITHUB_ENV
            echo "Longueur SECRET_KEY: ${#SECRET_KEY}"
          else
            echo "SECRET_KEY=undefined" >> $GITHUB_ENV
          fi

      - run: chmod +x gradlew
      - run: chmod +x .shell/publish_gen_to_maven_local.sh
      - run: ./gradlew test

  format:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - run: chmod +x format.sh
      - run: ./format.sh && git diff --exit-code
